/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2024-10-16T17:08:05.597749
 */
package bio.ferlab.clin.etl.model.raw


case class VCF_CNV_SVClustering_Parental_Origin(`contigName`: String = "chr1",
                                                `start`: Long = 9823628,
                                                `end`: Long = 9823687,
                                                `names`: Seq[String] = Seq("DRAGEN:LOSS:chr1:9823628-9823687"),
                                                `referenceAllele`: String = "A",
                                                `alternateAlleles`: Seq[String] = Seq("<DEL>"),
                                                `qual`: Double = 3.0,
                                                `filters`: Seq[String] = Seq("cnvQual"),
                                                `splitFromMultiAllelic`: Boolean = false,
                                                `INFO_END2`: Option[Int] = None,
                                                `INFO_STRANDS`: Option[String] = None,
                                                `INFO_CIEND`: Option[Seq[Int]] = None,
                                                `INFO_CIPOS`: Option[Seq[Int]] = None,
                                                `INFO_CHR2`: Option[String] = None,
                                                `INFO_SVLEN`: Seq[Int] = Seq(957),
                                                `INFO_REFLEN`: Int = 956,
                                                `INFO_ALGORITHMS`: Seq[String] = Seq("depth"),
                                                `INFO_END`: Option[Int] = None,
                                                `INFO_SVTYPE`: String = "CNV",
                                                `INFO_MEMBERS`: Seq[String] = Seq("DRAGEN:LOSS:chr1:9823628-9823687"),
                                                `genotypes`: Seq[GENOTYPES_CNV_SVCLUSTERING_PARENTAL_ORIGIN] = Seq(GENOTYPES_CNV_SVCLUSTERING_PARENTAL_ORIGIN()))

case class GENOTYPES_CNV_SVCLUSTERING_PARENTAL_ORIGIN(`sampleId`: String = "11111",
                                                      `SM`: Double = 0.685086,
                                                      `phased`: Boolean = false,
                                                      `calls`: Seq[Int] = Seq(0, 1),
                                                      `BC`: Int = 4,
                                                      `CN`: Int = 1,
                                                      `ECN`: Int = 2,
                                                      `PE`: Seq[Int] = Seq(2, 20))