/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2021-02-25T11:04:32.022
 */
package bio.ferlab.clin.etl.model.raw

import bio.ferlab.clin.etl.model.raw

case class VCF_SNV_Somatic_Input(`contigName`: String = "chr1",
                                 `start`: Long = 69896,
                                 `end`: Long = 69897,
                                 `names`: List[String] = List("rs200676709"),
                                 `referenceAllele`: String = "T",
                                 `alternateAlleles`: List[String] = List("C"),
                                 `qual`: Double = 2324.17,
                                 `splitFromMultiAllelic`: Boolean = false,
                                 `INFO_FILTERS`: List[String] = List("PASS"),
                                 `INFO_ReadPosRankSum`: Double = 0.736,
                                 `INFO_hotspot`: Option[Boolean] = Some(false),
                                 `INFO_DP`: Int = 330,
                                 `INFO_AQ`: Option[List[Double]] = Some(List(67.22)),
                                 `INFO_LOD`: Option[Double] = None,
                                 `INFO_MQ`: Double = 15.54,
                                 `INFO_END`: Option[Int] = None,
                                 `INFO_CSQ`: List[INFO_CSQ] = List(raw.INFO_CSQ()),
                                 `INFO_DB`: Boolean = true,
                                 `INFO_MQRankSum`: Double = 2.054,
                                 `INFO_FractionInformativeReads`: Option[Double] = Some(0.808),
                                 `INFO_OLD_MULTIALLELIC`: Option[String] = None,
                                 `genotypes`: List[SNV_SOMATIC_GENOTYPES] = List(SNV_SOMATIC_GENOTYPES(), SNV_SOMATIC_GENOTYPES(`sampleId` = "22222", `calls` = List(0, 0)), SNV_SOMATIC_GENOTYPES(`sampleId` = "33333")))


case class SNV_SOMATIC_GENOTYPES(`sampleId`: String = "11111",
                                 `SQ`: Option[List[Double]] = Some(List(56.08)),
                                 `F1R2`: List[Int] = List(0, 0),
                                 `PRI`: Option[List[Double]] = None,
                                 `SB`: Option[List[Int]] = Some(List(0, 0, 191, 141)),
                                 `F2R1`: List[Int] = List(0, 1),
                                 `alleleDepths`: List[Int] = List(0, 30),
                                 `ICNT`: Option[List[Int]] = None,
                                 `AF`: List[Double] = List(1.0),
                                 `phased`: Boolean = false,
                                 `calls`: List[Int] = List(0, 1),
                                 `depth`: Int = 1,
                                 `SPL`: Option[List[Int]] = None,
                                 `PS`: Option[Int] = None,
                                 `MB`: Option[List[Int]] = None)
