/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2021-08-02T14:32:47.728328
 */
package bio.ferlab.clin.model

import java.sql.Timestamp


case class GroupOutput(`id`: String = "ASHK-A",
                       `actual`: Boolean = true,
                       `resource_type`: String = "Group",
                       `type`: String = "person",
                       `ingestion_file_name`: String = "raw/landing/fhir/Group/Group_0_19000101_130549.json",
                       `ingested_on`: Timestamp = Timestamp.valueOf("1900-01-01 13:05:49.0"),
                       `version_id`: String = "1",
                       `updated_on`: Timestamp = Timestamp.valueOf("2021-07-26 11:47:02.979"),
                       `created_on`: Timestamp = Timestamp.valueOf("2021-07-26 11:47:02.979"),
                       `members`: List[MEMBERS] = List(MEMBERS(), MEMBERS("QA-PA-00002", false), MEMBERS("QA-PA-00003", false)),
                       `family_structure_code`: String = "TRI")

case class MEMBERS(`patient_id`: String = "QA-PA-00001",
                   `affected_status`: Boolean = true)
