/**
 * Generated by [[bio.ferlab.clin.testutils.ClassGenerator]]
 * on 2021-03-10T16:12:15.038
 */
package bio.ferlab.clin.model

import java.sql.Timestamp


case class GroupOutput(`actual`: Boolean = true,
                       `familyStructureCode`: String = "DUO",
                       `id`: String = "13636",
                       `resourceType`: String = "Group",
                       `type`: String = "person",
                       `ingestionFileName`: String = "raw/landing/fhir/Group/Group_0_20210310_130549.json",
                       `ingestedOn`: Timestamp = Timestamp.valueOf("2021-03-10 13:05:49.0"),
                       `versionId`: String = "1",
                       `updatedOn`: Timestamp = Timestamp.valueOf("2021-02-05 11:21:27.111"),
                       `createdOn`: Timestamp = Timestamp.valueOf("2021-02-05 11:21:27.111"),
                       `members`: List[String] = List("13634", "13635"))

