/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2022-02-21T15:25:03.816562
 */
package bio.ferlab.clin.model




case class ManeSummaryOutput(`NCBI_gene_id`: String = "GeneID:1",
                             `ensembl_gene_id`: String = "ENSG00000121410.12",
                             `HGNC_id`: String = "HGNC:5",
                             `symbol`: String = "A1BG",
                             `name`: String = "alpha-1-B glycoprotein",
                             `refseq_mrna_id`: String = "NM_130786.4",
                             `refseq_protein_id`: String = "NP_570602.2",
                             `ensembl_transcript_id`: String = "ENST00000263100.8",
                             `ensembl_feature_id`: String = "ENSP00000263100.2",
                             `MANE_status`: String = "MANE Select",
                             `GRCh38_chr`: String = "19",
                             `chr_start`: Long = 58345183,
                             `chr_end`: Long = 58353492,
                             `chr_strand`: String = "-",
                             `mane_select`: Boolean = true,
                             `mane_plus`: Boolean = false)

