/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2022-02-21T14:59:16.982653
 */
package bio.ferlab.clin.model




case class ManeSummaryInput(`#NCBI_GeneID`: String = "GeneID:1",
                            `Ensembl_Gene`: String = "ENSG00000121410.12",
                            `HGNC_ID`: String = "HGNC:5",
                            `symbol`: String = "A1BG",
                            `name`: String = "alpha-1-B glycoprotein",
                            `RefSeq_nuc`: String = "NM_130786.4",
                            `RefSeq_prot`: String = "NP_570602.2",
                            `Ensembl_nuc`: String = "ENST00000263100.8",
                            `Ensembl_prot`: String = "ENSP00000263100.2",
                            `MANE_status`: String = "MANE Select",
                            `GRCh38_chr`: String = "19",
                            `chr_start`: String = "58345183",
                            `chr_end`: String = "58353492",
                            `chr_strand`: String = "-")

