/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-11-19T10:13:50.022619
 */
package bio.ferlab.clin.model

import java.sql.Timestamp


case class ObservationOutput(`id`: String = "OB00001",
                             `note`: List[String] = List("une précision sur le CGH anormal"),
                             `resource_type`: String = "Observation",
                             `status`: String = "final",
                             `ingestion_file_name`: String = "/raw/landing/fhir/Observation/Observation_0_20211118_163103.json",
                             `ingested_on`: Timestamp = Timestamp.valueOf("2021-11-18 16:31:03.0"),
                             `version_id`: String = "1",
                             `updated_on`: Timestamp = Timestamp.valueOf("2021-11-16 00:18:52.146"),
                             `created_on`: Timestamp = Timestamp.valueOf("2021-11-16 00:18:52.146"),
                             `age_at_onset`: Option[String] = None,
                             `hpo_category`: Option[String] = None,
                             `observation_code`: String = "CGH",
                             `patient_id`: String = "PA00001",
                             `concept_code`: Option[String] = None,
                             `concept_description`: Option[String] = None,
                             `interpretation_code`: String = "A",
                             `interpretation_description`: String = "Abnormal",
                             `category_description`: Option[String] = None)

