/**
 * Generated by [[bio.ferlab.datalake.core.ClassGenerator]]
 * on 2021-03-08T08:58:19.067
 */
package bio.ferlab.clin.model

import java.sql.Timestamp


case class OrganizationOutput(//`organization_id`: String = "OR00207",
                              `id`: String = "OR00207",
                              `alias`: List[String] = List("CHUSJ"),
                              `name`: String = "CHU Sainte-Justine - Centre hospitalier universitaire mère-enfant",
                              `resource_type`: String = "Organization",
                              `code`: String = "prov",
                              `description`: String = "Healthcare Provider",
                              `ingestion_file_name`: String = "s3://clin/raw/landing/Organization/Organization_0_20210304_153643.json",
                              `ingested_on`: Timestamp = Timestamp.valueOf("2021-03-04 15:36:43.0"),
                              `version_id`: String = "53",
                              `updated_on`: Timestamp = Timestamp.valueOf("2020-12-17 13:14:12.758"),
                              `created_on`: Timestamp = Timestamp.valueOf("2020-12-17 13:14:12.758"))
