package bio.ferlab.clin.model

case class OrphanetGeneSetOutput(`orpha_code`: Long = 166024,
                                 `disorder_id`: Long = 17827,
                                 `expert_link`: String = "http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=166024",
                                 `name`: String = "Immunodeficiency due to a classical component pathway complement deficiency",
                                 `disorder_type_id`: Long = 21394,
                                 `disorder_type`: Option[String] = None,
                                 `disorder_group_id`: Long = 36547,
                                 `disorder_group`: Option[String] = None,
                                 `gene_source_of_validation`: String = "22587682[PMID]",
                                 `gene_id`: Long = 20160,
                                 `gene_symbol`: String = "OR4F5",
                                 `gene_name`: String = "kinesin family member 7",
                                 `gene_synonym_list`: List[String] = List("JBTS12"),
                                 `ensembl_gene_id`: String = "ENSG00000166813",
                                 `genatlas_gene_id`: String = "KIF7",
                                 `hgnc_gene_id`: String = "30497",
                                 `omim_gene_id`: String = "611254",
                                 `reactome_gene_id`: String = "Q2M1P5",
                                 `swiss_prot_gene_id`: String = "Q2M1P5",
                                 `association_type`: String = "Disease-causing germline mutation(s) in",
                                 `association_type_id`: Long = 17949,
                                 `association_status`: String = "Assessed",
                                 `gene_locus_id`: Long = 16859,
                                 `gene_locus`: String = "15q26.1",
                                 `gene_locus_key`: Long = 1,
                                 `average_age_of_onset`: List[String] = List("Infancy, Neonatal"),
                                 `average_age_of_death`: List[String] = List(),
                                 `type_of_inheritance`: List[String] = List("Autosomal recessive"))