/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-12-14T14:42:15.810010
 */
package bio.ferlab.clin.model




case class PanelOutput(`symbol`: String = "TRIM5",
                       `panels`: List[String] = List("DYSTM", "MITN"),
                       `version`: List[String] = List("MITN_v1", "NM_152490.5"))

