/**
 * Generated by [[bio.ferlab.datalake.core.ClassGenerator]]
 * on 2021-03-08T09:30:51.388
 */
package bio.ferlab.clin.model

import java.sql.Timestamp


case class PartitionerOutput(`id`: String = "PR00108",
                             `last_name`: String = "Gélinas",
                             `first_name`: String = "Clara",
                             `name_prefix`: String = "Dre.",
                             `name_suffix`: String = "",
                             `full_name`: String = "Dre. Clara Gélinas",
                             `medical_license_number`: String = "37512",
                             `resource_type`: String = "Practitioner",
                             `ingestion_file_name`: String = "file:///Users/christophe/ferlab/clin-variant-etl/target/scala-2.12/test-classes/raw/landing/Practitioner/Practitioner_0_20210305_082656.json",
                             `ingested_on`: Timestamp = Timestamp.valueOf("2021-03-05 08:26:56.0"),
                             `version_id`: String = "53",
                             `updated_on`: Timestamp = Timestamp.valueOf("2020-12-17 13:14:09.532"),
                             `created_on`: Timestamp = Timestamp.valueOf("2020-12-17 13:14:09.532"))

