/**
 * Generated by [[bio.ferlab.datalake.core.ClassGenerator]]
 * on 2021-03-11T08:58:30.250
 */
package bio.ferlab.clin.model

import java.sql.Timestamp


case class PartitionerRoleOutput(`active`: Boolean = true,
                                 `role_code`: String = "doctor",
                                 `role_description_EN`: String = "Doctor",
                                 `role_description_FR`: String = "Médecin prescripteur",
                                 `id`: String = "PROLE-c4becdcf-87e1-4fa7-ae87-9bbf555b1c4f",
                                 `organization_id`: String = "OR00210",
                                 `practitioner_id`: String = "c4becdcf-87e1-4fa7-ae87-9bbf555b1c4f",
                                 `resource_type`: String = "PractitionerRole",
                                 `phones`: List[PHONE] = List(PHONE(2, "1234"), PHONE(1, "514 123 4567")),
                                 `email_addresses`: List[String] = List("vferretti@ferlab.bio"),
                                 `ingestion_file_name`: String = "/raw/landing/fhir/PractitionerRole/PractitionerRole_0_19000101_102715.json",
                                 `ingested_on`: Timestamp = Timestamp.valueOf("2021-03-10 10:27:15.0"),
                                 `version_id`: String = "1",
                                 `updated_on`: Timestamp = Timestamp.valueOf("2021-02-16 07:20:53.773"),
                                 `created_on`: Timestamp = Timestamp.valueOf("2021-02-16 07:20:53.773"))

case class PHONE(rank: Long, phone_number: String)