/**
 * Generated by [[bio.ferlab.datalake.core.ClassGenerator]]
 * on 2021-03-11T08:58:30.250
 */
package bio.ferlab.clin.model

import java.sql.Timestamp


case class PartitionerRoleOutput(`active`: Boolean = true,
                                 `roleCode`: String = "doctor",
                                 `roleDescriptionEN`: String = "Doctor",
                                 `roleDescriptionFR`: String = "Médecin prescripteur",
                                 `id`: String = "PROLE-c4becdcf-87e1-4fa7-ae87-9bbf555b1c4f",
                                 `organizationId`: String = "OR00210",
                                 `practitionerId`: String = "c4becdcf-87e1-4fa7-ae87-9bbf555b1c4f",
                                 `resourceType`: String = "PractitionerRole",
                                 `phones`: List[PHONE] = List(PHONE(2, "1234"), PHONE(1, "514 123 4567")),
                                 `emailAddresses`: List[String] = List("vferretti@ferlab.bio"),
                                 `ingestionFileName`: String = "/raw/landing/fhir/PractitionerRole/PractitionerRole_0_20210310_102715.json",
                                 `ingestedOn`: Timestamp = Timestamp.valueOf("2021-03-10 10:27:15.0"),
                                 `versionId`: String = "1",
                                 `updatedOn`: Timestamp = Timestamp.valueOf("2021-02-16 07:20:53.773"),
                                 `createdOn`: Timestamp = Timestamp.valueOf("2021-02-16 07:20:53.773"))

case class PHONE(rank: Long, phoneNumber: String)