/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-03-08T09:27:17.176
 */
package bio.ferlab.clin.model

import java.sql.{Date, Timestamp}


case class PatientOutput(//`patient_id`: String = "17771",
                         `id`: String = "17771",
                         `ingested_on`: Timestamp = Timestamp.valueOf("2021-03-05 08:26:56.0"),
                         `family_id`: String = "17772",
                         `active`: Boolean = true,
                         `birth_date`: Date = Date.valueOf("2021-02-01"),
                         `gender`: String = "male",
                         `practitioner_id`: String = "PROLE-78a60801-cbab-4064-93c6-d85aeadc1edb",
                         `medical_record_number`: String = "1234",
                         `jurisdictional_health_number`: String = "ABCD123455676",
                         `organization_id`: String = "CHUSJ",
                         `resource_type`: String = "Patient",
                         `ingestion_file_name`: String = "/raw/landing/fhir/Patient/Patient_2_20210305_082656.json",
                         `last_name`: String = "tset",
                         `first_name`: String = "sdfsd",
                         `full_name`: String = "sdfsd tset",
                         `version_id`: String = "1",
                         `updated_on`: Timestamp = Timestamp.valueOf("2021-02-15 11:55:04.06"),
                         `created_on`: Timestamp = Timestamp.valueOf("2021-02-15 11:55:04.06"),
                         `is_proband`: Boolean = true,
                         `is_fetus`: Boolean = false)
