/**
 * Generated by [[bio.ferlab.datalake.core.ClassGenerator]]
 * on 2021-03-08T09:27:17.176
 */
package bio.ferlab.clin.model

import java.sql.{Date, Timestamp}


case class PatientOutput(`id`: String = "17771",
                         `ingestedOn`: Timestamp = Timestamp.valueOf("2021-03-05 08:26:56.0"),
                         `family-id`: String = "17772",
                         `active`: Boolean = true,
                         `birthDate`: Date = Date.valueOf("2021-02-01"),
                         `gender`: String = "male",
                         `practitionerId`: String = "PROLE-78a60801-cbab-4064-93c6-d85aeadc1edb",
                         `medical_record_number`: String = "1234",
                         `jurisdictional_health_number`: String = "ABCD123455676",
                         `organizationId`: String = "CHUSJ",
                         `resourceType`: String = "Patient",
                         `ingestionFileName`: String = "/raw/landing/fhir/Patient/Patient_2_20210305_082656.json",
                         `last_name`: String = "tset",
                         `first_name`: String = "sdfsd",
                         `full_name`: String = "sdfsd tset",
                         `versionId`: String = "1",
                         `updatedOn`: Timestamp = Timestamp.valueOf("2021-02-15 11:55:04.06"),
                         `createdOn`: Timestamp = Timestamp.valueOf("2021-02-15 11:55:04.06"),
                         `is-proband`: Boolean = true,
                         `is-fetus`: Boolean = false)
