/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-08-02T15:52:57.380586
 */
package bio.ferlab.clin.model

import java.sql.{Date, Timestamp}


case class PatientOutput(`id`: String = "QA-PA-00002",
                         `ingested_on`: Timestamp = Timestamp.valueOf("1900-01-01 10:27:15.0"),
                         `medical_record_number`: String = "123456789",
                         `active`: Boolean = true,
                         `birth_date`: Date = Date.valueOf("1970-01-30"),
                         `gender`: String = "female",
                         `resource_type`: String = "Patient",
                         `ingestion_file_name`: String = "file:///Users/christophebotek/ferlab/clin-variant-etl/src/test/resources/raw/landing/fhir/Patient/Patient_1_19000101_102715.json",
                         `version_id`: String = "1",
                         `updated_on`: Timestamp = Timestamp.valueOf("2021-07-26 11:47:02.979"),
                         `created_on`: Timestamp = Timestamp.valueOf("2021-07-26 11:47:02.979"),
                         `jurisdictional_health_number`: String = "SHEK70513014",
                         `practitioner_id`: String = "PROLE-1eb97008-b3a6-47c2-ac60-c54e66e0c491",
                         `organization_id`: String = "CHUSJ",
                         `family_id`: String = "ASHK-A",
                         `is_fetus`: Boolean = false,
                         `is_proband`: Boolean = false,
                         `family_relationship`: List[FAMILY_RELATIONSHIP] = List(FAMILY_RELATIONSHIP(), FAMILY_RELATIONSHIP("QA-PA-00005", "DAU")))

case class FAMILY_RELATIONSHIP(`patient2`: String = "QA-PA-00001",
                               `patient1_to_patient2_relation`: String = "MTH")
