/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2021-11-19T11:17:09.057194
 */
package bio.ferlab.clin.model

import java.sql.Timestamp


case class PractitionerRoleOutput(`active`: Boolean = true,
                                  `id`: String = "PRR00101",
                                  `resource_type`: String = "PractitionerRole",
                                  `ingestion_file_name`: String = "/raw/landing/fhir/PractitionerRole/PractitionerRole_0_20211118_163103.json",
                                  `ingested_on`: Timestamp = Timestamp.valueOf("2021-11-18 16:31:03.0"),
                                  `version_id`: String = "1",
                                  `updated_on`: Timestamp = Timestamp.valueOf("2021-11-16 00:18:52.146"),
                                  `created_on`: Timestamp = Timestamp.valueOf("2021-11-16 00:18:52.146"),
                                  `phone_numbers`: List[String] = List("514-564-3099"),
                                  `email_addresses`: List[String] = List("Champagne.Jacob@CHUSJ.org"),
                                  `practitioner_id`: String = "PR00101",
                                  `organization_id`: String = "CHUSJ",
                                  `role_code`: String = "doctor",
                                  `role_description`: String = "Doctor")
