/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-11-19T13:52:17.684048
 */
package bio.ferlab.clin.model

import java.sql.{Date, Timestamp}


case class ServiceRequestOutput(`authored_on`: Option[Date] = None,
                                `id`: String = "SR0004",
                                `intent`: String = "order",
                                `note`: List[NOTE] = List(NOTE()),
                                `priority`: String = "routine",
                                `resource_type`: String = "ServiceRequest",
                                `status`: String = "active",
                                `ingestion_file_name`: String = "file:///Users/christophebotek/ferlab/clin-variant-etl/src/test/resources/raw/landing/fhir/ServiceRequest/ServiceRequest_0_20211118_163103.json",
                                `ingested_on`: Timestamp = Timestamp.valueOf("2021-11-18 16:31:03.0"),
                                `version_id`: String = "4",
                                `updated_on`: Timestamp = Timestamp.valueOf("2021-11-17 18:24:58.446"),
                                `created_on`: Timestamp = Timestamp.valueOf("2021-11-17 18:24:58.446"),
                                `specimens`: List[String] = List("32736", "32737", "32738"),
                                `service_request_code`: String = "DI",
                                `service_request_description`: String = "Déficience intellectuelle (Trio)",
                                `patient_id`: String = "PA00004",
                                `practitioner_id`: String = "PR00101",
                                `clinical_impression_id`: String = "CI00404",
                                `is_submitted`: Boolean = true)

case class NOTE(`text`: String = "Un commentaire général sur cette prescription",
                `time`: Option[Timestamp] = None,
                `practitioner_id`: String = "PR00101")
