/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-11-25T15:57:23.720689
 */
package bio.ferlab.clin.model

import java.sql.{Date, Timestamp}


case class ServiceRequestOutput(`authored_on`: Option[Date] = None,
                                `id`: String = "SR0095",
                                `intent`: String = "order",
                                `note`: List[NOTE] = List(NOTE()),
                                `priority`: String = "routine",
                                `resource_type`: String = "ServiceRequest",
                                `status`: String = "active",
                                `ingestion_file_name`: String = "/raw/landing/fhir/ServiceRequest/ServiceRequest_0_20211124_143455.json",
                                `ingested_on`: Timestamp = Timestamp.valueOf("2021-11-24 14:34:55.0"),
                                `version_id`: String = "2",
                                `updated_on`: Timestamp = Timestamp.valueOf("2021-11-23 09:40:49.947"),
                                `created_on`: Timestamp = Timestamp.valueOf("2021-11-23 09:40:49.947"),
                                `specimens`: List[String] = List("109672", "109673"),
                                `service_request_code`: String = "MM_PG",
                                `service_request_description`: String = "Maladies musculaires (Panel global)",
                                `patient_id`: String = "PA00095",
                                `practitioner_id`: String = "PR00117",
                                `clinical_impression_id`: String = "CI00495",
                                `is_submitted`: Boolean = true)

case class NOTE(`text`: String = "Un commentaire général sur cette prescription",
                `time`: Option[Timestamp] = None,
                `practitioner_id`: String = "PR00117")
