/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2021-11-19T14:02:18.947641
 */
package bio.ferlab.clin.model

import java.sql.Timestamp


case class SpecimenOutput(`id`: String = "32738",
                          `resource_type`: String = "Specimen",
                          `ingestion_file_name`: String = "/raw/landing/fhir/Specimen/Specimen_0_20211118_163103.json",
                          `ingested_on`: Timestamp = Timestamp.valueOf("2021-11-18 16:31:03.0"),
                          `version_id`: String = "1",
                          `updated_on`: Timestamp = Timestamp.valueOf("2021-11-16 00:43:11.573"),
                          `created_on`: Timestamp = Timestamp.valueOf("2021-11-16 00:43:11.573"),
                          `parent_id`: String = "32737",
                          `organization_id`: String = "CQGC",
                          `specimen_id`: Option[String] = None,
                          `sample_id`: Option[String] = None,
                          `aliquot_id`: String = "16777",
                          `patient_id`: String = "PA00004",
                          `service_request_id`: String = "SR0004",
                          `received_time`: Timestamp = Timestamp.valueOf("2021-11-16 00:32:56.0"),
                          `specimen_type`: String = "DNA")

