/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-08-03T15:27:14.994853
 */
package bio.ferlab.clin.model

import java.sql.Timestamp


case class SpecimenOutput(`id`: String = "73260",
                          `resource_type`: String = "Specimen",
                          `ingestion_file_name`: String = "raw/landing/fhir/Specimen/Specimen_0_19000101_000000.json",
                          `ingested_on`: Timestamp = Timestamp.valueOf("1900-01-01 00:00:00.000"),
                          `version_id`: String = "1",
                          `updated_on`: Timestamp = Timestamp.valueOf("2021-08-02 17:29:30.584"),
                          `created_on`: Timestamp = Timestamp.valueOf("2021-08-02 17:29:30.584"),
                          `parent_id`: String = "73259",
                          `organization_id`: String = "71615",
                          `specimen_id`: Option[String] = None,
                          `sample_id`: Option[String] = None,
                          `aliquot_id`: String = "8888888",
                          `patient_id`: String = "37705",
                          `service_request_id`: String = "38390",
                          `received_time`: Timestamp = Timestamp.valueOf("2021-08-02 17:29:28.0"),
                          `specimen_type`: String = "NBL")

