/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2021-11-24T15:02:22.406412
 */
package bio.ferlab.clin.model

import java.sql.{Date, Timestamp}


case class TaskOutput(`id`: String = "109351",
                      `intent`: String = "order",
                      `priority`: String = "routine",
                      `resource_type`: String = "Task",
                      `status`: String = "completed",
                      `ingestion_file_name`: String = "/raw/landing/fhir/Task/Task_0_19000101_000000.json",
                      `ingested_on`: Timestamp = Timestamp.valueOf("1900-01-01 00:00:00.0"),
                      `version_id`: String = "1",
                      `updated_on`: Timestamp = Timestamp.valueOf("2021-11-23 09:40:49.947"),
                      `created_on`: Timestamp = Timestamp.valueOf("2021-11-23 09:40:49.947"),
                      `analysis_code`: String = "GEAN",
                      `service_request_id`: String = "SR0095",
                      `patient_id`: String = "PA00095",
                      `organization_id`: String = "LDM-CHUSJ",
                      `specimen_id`: String = "109673",
                      `documents`: List[DOCUMENTS] = List(DOCUMENTS(), DOCUMENTS("109349", "VCF File"), DOCUMENTS("109350", "QC File")),
                      `authored_on`: Timestamp = Timestamp.valueOf("2021-11-23 09:33:05.0"),
                      `experiment`: EXPERIMENT = EXPERIMENT(),
                      `workflow`: WORKFLOW = WORKFLOW())

case class WORKFLOW(`genome_build`: String = "GRCh38",
                    `name`: String = "Dragen",
                    `version`: String = "3.8.4")

case class EXPERIMENT(`sequencing_strategy`: String = "WXS",
                      `name`: String = "201106_A00516_0169_AHFM3HDSXY",
                      `alias`: String = "A00516_0169",
                      `platform`: String = "Illumina NovaSeq",
                      `capture_kit`: String = "RocheKapaHyperExome",
                      `sequencer_id`: String = "A00516",
                      `aliquot_id`: String = "16868",
                      `run_date`: Date = Date.valueOf("2020-11-06"))

case class DOCUMENTS(`id`: String = "109348",
                     `document_type`: String = "CRAM File")
