/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-08-03T16:34:11.811230
 */
package bio.ferlab.clin.model

import java.sql.Timestamp


case class TaskOutput(`code`: String = "SA",
                      `id`: String = "73255",
                      `intent`: String = "order",
                      `priority`: String = "routine",
                      `resource_type`: String = "Task",
                      `status`: String = "completed",
                      `ingestion_file_name`: String = "/raw/landing/fhir/Task/Task_0_19000101_000000.json",
                      `ingested_on`: Timestamp = Timestamp.valueOf("1900-01-01 00:00:00.0"),
                      `version_id`: String = "1",
                      `updated_on`: Timestamp = Timestamp.valueOf("2021-08-02 17:29:30.584"),
                      `created_on`: Timestamp = Timestamp.valueOf("2021-08-02 17:29:30.584"),
                      `organization_id`: String = "OR00215",
                      `specimen_id`: String = "73260",
                      `document_id`: String = "73252",
                      `patient_id`: String = "37705",
                      `service_request_id`: String = "38390",
                      `authored_on`: Timestamp = Timestamp.valueOf("2021-08-02 17:29:28.0"),
                      `sequencing_experiment`: String = "WXS")

