/**
 * Generated by [[bio.ferlab.datalake.spark3.ClassGenerator]]
 * on 2021-11-19T14:06:31.407506
 */
package bio.ferlab.clin.model

import java.sql.Timestamp


case class TaskOutput(`code`: String = "SA",
                      `id`: String = "31980",
                      `intent`: String = "order",
                      `priority`: String = "routine",
                      `resource_type`: String = "Task",
                      `status`: String = "completed",
                      `ingestion_file_name`: String = "/raw/landing/fhir/Task/Task_0_20211118_163103.json",
                      `ingested_on`: Timestamp = Timestamp.valueOf("2021-11-18 16:31:03.0"),
                      `version_id`: String = "1",
                      `updated_on`: Timestamp = Timestamp.valueOf("2021-11-16 00:43:11.573"),
                      `created_on`: Timestamp = Timestamp.valueOf("2021-11-16 00:43:11.573"),
                      `organization_id`: String = "LDM-CHUSJ",
                      `specimen_id`: String = "32738",
                      `document_id`: String = "31977",
                      `patient_id`: String = "PA00004",
                      `service_request_id`: String = "SR0004",
                      `authored_on`: Timestamp = Timestamp.valueOf("2021-11-16 00:32:56.0"),
                      `experiment`: EXPERIMENT = EXPERIMENT(),
                      `workflow`: WORKFLOW = WORKFLOW())

case class EXPERIMENT(`sequencing_strategy`: String = "WXS",
                      `name`: String = "201106_A00516_0169_AHFM3HDSXY",
                      `alias`: String = "A00516_0169",
                      `platform`: String = "Illumina NovaSeq",
                      `capture_kit`: String = "RocheKapaHyperExome",
                      `sequencer_id`: String = "A00516",
                      `run_date`: Option[Timestamp] = None)

case class WORKFLOW(`genome_build`: String = "GRCh38",
                    `name`: String = "Dragen",
                    `version`: String = "3.8.4")
