/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2021-02-24T14:16:04.977
 */
package bio.ferlab.clin.model

case class VariantIndexUpdate(`chromosome`: String = "1",
                              `start`: Long = 69897,
                              `reference`: String = "T",
                              `alternate`: String = "C",
                              `donors`: List[DONORS] = List(DONORS(), DONORS(`organization_id` = "OR00202")))
