/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2021-11-19T14:02:18.947641
 */
package bio.ferlab.clin.model.normalized.fhir

import java.sql.Timestamp

case class NormalizedSpecimen(`id`: String = "134658",
                              `resource_type`: String = "Specimen",
                              `ingestion_file_name`: String = "/raw/landing/fhir/Specimen/Specimen_0_20211118_163103.json",
                              `ingested_on`: Timestamp = Timestamp.valueOf("2021-11-18 16:31:03.0"),
                              `version_id`: String = "1",
                              `updated_on`: Timestamp = Timestamp.valueOf("2021-11-16 00:43:11.573"),
                              `created_on`: Timestamp = Timestamp.valueOf("2021-11-16 00:43:11.573"),
                              `parent_id`: String = "134657",
                              `organization_id`: String = "LDM-CHUSJ",
                              `specimen_id`: Option[String] = None,
                              `sample_id`: Option[String] = Some("14-696"),
                              `patient_id`: String = "PA00049",
                              `service_request_id`: String = "SR0049",
                              `received_time`: Timestamp = Timestamp.valueOf("2021-11-16 00:32:56.0"),
                              `specimen_type`: String = "DNA")

