/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2025-02-20T13:13:52.867141
 */
package bio.ferlab.clin.model.normalized.fhir

import java.sql.Timestamp


case class NormalizedCodeSystem(`resource_type`: String = "CodeSystem",
                                `id`: String = "variant-type",
                                `url`: String = "http://fhir.cqgc.ferlab.bio/CodeSystem/variant-type",
                                `version`: String = "0.1.0",
                                `name`: String = "variant-type",
                                `title`: String = "Variant types",
                                `status`: String = "active",
                                `experimental`: Boolean = false,
                                `publisher`: String = "Ferlab.bio",
                                `description`: String = "Variant types",
                                `caseSensitive`: Boolean = true,
                                `content`: String = "complete",
                                `ingestion_file_name`: String = "/raw/landing/fhir/CodeSystem/CodeSystem_0_19000101_000000.json",
                                `ingested_on`: Timestamp = java.sql.Timestamp.valueOf("1900-01-01 00:00:00.0"),
                                `version_id`: String = "1",
                                `updated_on`: Timestamp = java.sql.Timestamp.valueOf("2025-01-15 21:10:56.229"),
                                `created_on`: Timestamp = java.sql.Timestamp.valueOf("2025-01-15 21:10:56.229"),
                                `profile`: Option[String] = None,
                                `concept_code`: String = "S",
                                `concept_description`: String = "Somatic",
                                `concept_fr_description`: String = "Somatique",
                                `concept_definition`: String = "Somatic variant")

