/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2021-11-19T10:36:13.664191
 */
package bio.ferlab.clin.model.normalized.fhir

import java.sql.{Date, Timestamp}


case class NormalizedPerson(`id`: String = "864",
                            `ingested_on`: Timestamp = Timestamp.valueOf("2021-11-18 16:31:03.0"),
                            `first_name`: String = "Jane",
                            `last_name`: String = "Doe",
                            `birth_date`: Date = Date.valueOf("2001-03-06"),
                            `gender`: String = "female",
                            `resource_type`: String = "Person",
                            `ingestion_file_name`: String = "/raw/landing/fhir/Person/Person_0_20230709_102715.json",
                            `version_id`: String = "1",
                            `updated_on`: Timestamp = Timestamp.valueOf("2024-12-09 16:21:05.281"),
                            `created_on`: Timestamp = Timestamp.valueOf("2021-11-17 17:29:55.843"),
                            `jurisdictional_health_number`: String = "ABCE12345679",
                            `patient_ids`: Seq[String] = Seq("PA00004", "PA00005", "PA00006")
                           )
