/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2021-11-19T10:22:01.926447
 */
package bio.ferlab.clin.model.normalized.fhir

import java.sql.Timestamp


case class NormalizedOrganization(`alias`: List[String] = List("CHUSJ"),
                                  `id`: String = "CHUSJ",
                                  `name`: String = "Centre hospitalier universitaire Sainte-Justine",
                                  `resource_type`: String = "Organization",
                                  `ingestion_file_name`: String = "/raw/landing/fhir/Organization/Organization_0_20211118_163103.json",
                                  `ingested_on`: Timestamp = Timestamp.valueOf("2021-11-18 16:31:03.0"),
                                  `version_id`: String = "1",
                                  `updated_on`: Timestamp = Timestamp.valueOf("2021-11-16 00:18:52.146"),
                                  `created_on`: Timestamp = Timestamp.valueOf("2021-11-16 00:18:52.146"),
                                  `code`: String = "prov",
                                  `description`: String = "Healthcare Provider")

