/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2024-10-24T13:34:49.739093
 */
package bio.ferlab.clin.model.nextflow

case class SVClustering(`chromosome`: String = "1",
                        `start`: Long = 9823629,
                        `end`: Long = 9823688,
                        `reference`: String = "A",
                        `alternate`: String = "<DEL>",
                         `name`: String = "DRAGEN:DUP:chr1:9823628-9823687",
                        `members`: Seq[String] = Seq("DRAGEN:LOSS:chr1:9823628-9823687"),
                        `frequency_RQDM`: FREQUENCY_RQDM = FREQUENCY_RQDM())

case class FREQUENCY_RQDM(`pn`: Long = 5,
                          `pc`: Long = 2,
                          `pf`: Double = 0.4)
