/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2025-04-02T12:32:03.859012
 */
package bio.ferlab.clin.model.nextflow

case class SVClusteringSomatic(`chromosome`: String = "1",
                               `start`: Long = 9823629,
                               `end`: Long = 9823688,
                               `reference`: String = "A",
                               `alternate`: String = "<DEL>",
                               `name`: String = "DRAGEN:LOSS:chr1:9823628-9823687",
                               `members`: Seq[String] = Seq("DRAGEN:LOSS:chr1:9823628-9823687"),
                               `frequency_RQDM`: FREQUENCY_RQDM_SOM = FREQUENCY_RQDM_SOM())

case class FREQUENCY_RQDM_SOM(`som`: SOM = SOM())

case class SOM(`pc`: Long = 1,
               `pn`: Long = 1,
               `pf`: Double = 1.0)