/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2025-04-02T12:32:03.859012
 */
package bio.ferlab.clin.model.nextflow

case class SVClusteringGermline(`chromosome`: String = "1",
                                `start`: Long = 9823629,
                                `end`: Long = 9823688,
                                `reference`: String = "A",
                                `alternate`: String = "<DEL>",
                                `name`: String = "DRAGEN:LOSS:chr1:9823628-9823687",
                                `members`: Seq[String] = Seq("DRAGEN:LOSS:chr1:9823628-9823687"),
                                `aliquot_ids`: Set[String] = Set("1", "2", "3", "4"),
                                `frequency_RQDM`: FREQUENCY_RQDM_GERM = FREQUENCY_RQDM_GERM())

case class FREQUENCY_RQDM_GERM(`germ`: GERM = GERM())

case class GERM(`affected`: AFFECTED = AFFECTED(),
                `non_affected`: NON_AFFECTED = NON_AFFECTED(),
                `total`: TOTAL = TOTAL())

case class AFFECTED(`pc`: Long = 1,
                    `pn`: Long = 1,
                    `pf`: Double = 1.0)

case class NON_AFFECTED(`pc`: Long = 0,
                        `pn`: Long = 1,
                        `pf`: Double = 0.0)

case class TOTAL(`pc`: Long = 1,
                 `pn`: Long = 1,
                 `pf`: Double = 1.0)