/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2023-05-09T16:43:07.650807
 */
package bio.ferlab.clin.model.raw




case class RawExomiser(`#RANK`: String = "3",
                       `ID`: String = "X-111736800-A-G_XR",
                       `GENE_SYMBOL`: String = "ALG13",
                       `ENTREZ_GENE_ID`: String = "79868",
                       `MOI`: String = "XR",
                       `P-VALUE`: String = "0.0056",
                       `EXOMISER_GENE_COMBINED_SCORE`: String = "0.9008",
                       `EXOMISER_GENE_PHENO_SCORE`: String = "0.9092",
                       `EXOMISER_GENE_VARIANT_SCORE`: String = "0.6581",
                       `EXOMISER_VARIANT_SCORE`: String = "0.6581",
                       `CONTRIBUTING_VARIANT`: String = "1",
                       `WHITELIST_VARIANT`: String = "0",
                       `VCF_ID`: String = "rs764400701",
                       `RS_ID`: String = "rs764400701",
                       `CONTIG`: String = "X",
                       `START`: String = "111736800",
                       `END`: String = "111736800",
                       `REF`: String = "A",
                       `ALT`: String = "G",
                       `CHANGE_LENGTH`: String = "0",
                       `QUAL`: String = "218.2100",
                       `FILTER`: String = "PASS",
                       `GENOTYPE`: String = "0:0/1:1",
                       `FUNCTIONAL_CLASS`: String = "synonymous_variant",
                       `HGVS`: String = "ALG13:NM_001099922.2:c.2616A>G:p.(=)",
                       `EXOMISER_ACMG_CLASSIFICATION`: String = "UNCERTAIN_SIGNIFICANCE",
                       `EXOMISER_ACMG_EVIDENCE`: String = "PP4,BP6",
                       `EXOMISER_ACMG_DISEASE_ID`: String = "ORPHA:777",
                       `EXOMISER_ACMG_DISEASE_NAME`: String = "X-linked non-syndromic intellectual disability",
                       `CLINVAR_ALLELE_ID`: String = "689327",
                       `CLINVAR_PRIMARY_INTERPRETATION`: String = "BENIGN",
                       `CLINVAR_STAR_RATING`: String = "1",
                       `GENE_CONSTRAINT_LOEUF`: String = "0.050979",
                       `GENE_CONSTRAINT_LOEUF_LOWER`: String = "0.02",
                       `GENE_CONSTRAINT_LOEUF_UPPER`: String = "0.16",
                       `MAX_FREQ_SOURCE`: String = "UK10K",
                       `MAX_FREQ`: String = "0.0303",
                       `ALL_FREQ`: String = "TOPMED=0.003778,UK10K=0.0303,EXAC_AMERICAN=0.021528525,EXAC_NON_FINNISH_EUROPEAN=0.0042069834,GNOMAD_E_AMR=0.011359763,GNOMAD_E_NFE=0.00386578,GNOMAD_G_NFE=0.009470594",
                       `MAX_PATH_SOURCE`: String = "CADD",
                       `MAX_PATH`: String = "0.6608436",
                       `ALL_PATH`: String = "CADD=0.6608436")

