/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2023-11-24T17:06:24.457101
 */
package bio.ferlab.clin.model.normalized


case class NormalizedFranklin(`chromosome`: String = "1",
                              `start`: Long = 100960420,
                              `end`: Long = 100960420,
                              `reference`: String = "C",
                              `alternate`: String = "A",
                              `batch_id`: String = "BAT1",
                              `family_id`: Option[String] = Some("1"),
                              `aliquot_id`: Option[String] = Some("1"),
                              `analysis_id`: String = "1",
                              `score`: Double = 0.0036969461275872164,
                              `acmg_classification`: String = "UNCERTAIN_SIGNIFICANCE",
                              `link`: String = "https://franklin.genoox.com/clinical-db/variant/snp/chr7-100960420-C-A-HG38",
                              `acmg_evidence`: Set[String] = Set("PS1", "PS3"))

