/**
 * Generated by [[bio.ferlab.datalake.spark3.utils.ClassGenerator]]
 * on 2023-05-09T17:04:31.514061
 */
package bio.ferlab.clin.model.normalized




case class NormalizedExomiser(`chromosome`: String = "X",
                              `start`: Long = 111736800,
                              `end`: Long = 111736800,
                              `reference`: String = "A",
                              `alternate`: String = "G",
                              `id`: String = "X-111736800-A-G_XR",
                              `aliquot_id`: String = "aliquot1",
                              `rank`: Int = 3,
                              `gene_symbol`: String = "ALG13",
                              `entrez_gene_id`: Long = 79868,
                              `exomiser_variant_score`: Float = 0.6581f,
                              `gene_combined_score`: Float = 0.9008f,
                              `contributing_variant`: Boolean = true,
                              `moi`: String = "XR",
                              `acmg_classification`: String = "UNCERTAIN_SIGNIFICANCE",
                              `acmg_evidence`: Seq[String] = Seq("PP4","BP6"),
                              `batch_id`: String = "BAT1")

