/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2024-03-20T11:02:31.894221
 */
package bio.ferlab.clin.model.enriched

case class EnrichedClinical(`service_request_id`: String = "SRS0001",
                            `patient_id`: String = "PA0001",
                            `analysis_service_request_id`: String = "SRA0001",
                            `batch_id`: String = "BAT1",
                            `bioinfo_analysis_code`: String = "GEAN",
                            `aliquot_id`: String = "1",
                            `sequencing_strategy`: String = "WXS",
                            `genome_build`: String = "GRCh38",
                            `analysis_code`: String = "MMG",
                            `analysis_display_name`: Option[String] = None,
                            `affected_status`: Boolean = true,
                            `affected_status_code`: String = "affected",
                            `is_proband`: Boolean = true,
                            `gender`: String = "Male",
                            `practitioner_role_id`: String = "PPR00101",
                            `organization_id`: String = "CHUSJ",
                            `family_id`: Option[String] = Some("FM00001"),
                            `mother_id`: Option[String] = Some("PA0003"),
                            `father_id`: Option[String] = Some("PA0002"),
                            `mother_aliquot_id`: Option[String] = Some("3"),
                            `father_aliquot_id`: Option[String] = Some("2"),
                            `specimen_id`: String = "SP_0001",
                            `sample_id`: String = "SA_0001",
                            `covgene_urls`: Option[Set[String]] = None,
                            `exomiser_urls`: Option[Set[String]] = None,
                           )

