/**
 * Generated by [[bio.ferlab.datalake.testutils.ClassGenerator]]
 * on 2024-03-20T11:02:31.894221
 */
package bio.ferlab.clin.model.enriched

import java.sql.Date

case class EnrichedClinical(`sequencing_id`: String = "SRS0001",
                            `patient_id`: String = "PA0001",
                            `person_id`: Option[String] = None,
                            `analysis_id`: String = "SRA0001",
                            `batch_id`: String = "BAT1",
                            `bioinfo_analysis`: String = "germline",
                            `bioinfo_analysis_code`: String = "GEBA",
                            `aliquot_id`: String = "1",
                            `sequencing_strategy`: String = "WXS",
                            `genome_build`: String = "GRCh38",
                            `analysis_code`: String = "MMG",
                            `analysis_display_name`: Option[String] = None,
                            `affected_status`: Boolean = true,
                            `affected_status_code`: String = "affected",
                            `is_proband`: Boolean = true,
                            `gender`: String = "Male",
                            `practitioner_role_id`: String = "PPR00101",
                            `organization_id`: String = "CHUSJ",
                            `family_id`: Option[String] = Some("FM00001"),
                            `mother_id`: Option[String] = Some("PA0003"),
                            `father_id`: Option[String] = Some("PA0002"),
                            `mother_aliquot_id`: Option[String] = Some("3"),
                            `father_aliquot_id`: Option[String] = Some("2"),
                            `specimen_id`: String = "SP_0001",
                            `sample_id`: String = "SA_0001",
                            `clinical_signs`: Option[Set[ClinicalSign]] = Some(Set(ClinicalSign())),
                            `covgene_urls`: Option[Set[String]] = None,
                            `exomiser_urls`: Option[Set[String]] = None,
                            `exomiser_cnv_urls`: Option[Set[String]] = None,
                            `cnv_vcf_urls`: Option[Set[String]] = None,
                            `snv_vcf_urls`: Option[Set[String]] = None,
                            `birth_date`: Option[Date] = None,
                            `first_name`: Option[String] = None,
                           )

case class ClinicalSign(`id`: String = "HP:0001347",
                        `name`: String = "Hyperreflexia",
                        `affected_status_code`: String = "affected",
                        `affected_status`: Boolean = true,
                       )

